export type UsefulLink = {
  name: string;
  url: string;
};

export const usefulLinks: UsefulLink[] = [
  { name: 'Earn Free Gift Cards and Cash with Online Paid Surveys | Swagbucks', url: 'https://www.swagbucks.com/' },
  { name: 'Remotasks', url: 'https://www.remotasks.com/en/dashboard?is_new_user=1' },
  { name: 'Userlytics - The most advanced User Testing Platform | Login', url: 'https://dashboard.userlytics.com/tester/' },
  { name: 'Halaman Kontribusi - Mongabay.co.id', url: 'https://mongabay.co.id/halaman-kontribusi/' },
  { name: 'Sell photos, footage clips, illustrations & vectors | Shutterstock', url: 'https://submit.shutterstock.com/' },
  { name: 'Google AI Studio', url: 'https://aistudio.google.com/u/3/apps/drive/1KAw34KH5tAEDchMBZdpzn6aY1vWO4S2U?source=start&showAssistant=true&showPreview=true&resourceKey=' },
  { name: 'Fokus Sobri Tiap Hari - Blog Dokter Sobri', url: 'https://blogdoktersobri.blogspot.com/2025/07/fokus-sobri-tiap-hari.html' },
  { name: 'Latihan Sobri - Muhammad Sobri Maulana - Medium', url: 'https://muhammadsobrimaulana31.medium.com/latihan-sobri-956cbcaf3027' },
  { name: 'Belajar Sobri Tiap Hari - Google Dokumen', url: 'https://docs.google.com/document/d/1JOpEORGiTd6X49flrpYJYkFlhZl3j13-3Wr3r8g2ZYc/edit?tab=t.0' },
  { name: 'LMS Kemkes', url: 'https://lms.kemkes.go.id/' },
  { name: 'SENAM AEROBIK HANYA 15 MENIT MEMBAKAR LEMAK UNTUK PEMULA - YouTube', url: 'https://www.youtube.com/watch?v=vSThNlE1snE' },
  { name: 'Yanto Tanjung - YouTube', url: 'https://www.youtube.com/@Yantotanjung' },
  { name: 'Rahasia Sobri. 1. Ingin Kaya? | by Muhammad Sobri Maulana | Feb, 2025 | Medium', url: 'https://muhammadsobrimaulana31.medium.com/rahasia-sobri-b680b8305fca' },
  { name: 'Rutin Doa Pagi-Malam', url: 'https://duniadoktersobri.blogspot.com/2024/12/rutin-doa-pagi-malam.html' },
  { name: 'Doa Sobri Rutin Rezeki. Allaahumma innee as’aluka ‘ilman… | by Muhammad Sobri Maulana | Sep, 2024 | Medium', url: 'https://muhammadsobrimaulana31.medium.com/doa-sobri-rutin-rezeki-af06cf7b9f97' },
  { name: 'Pendaftaran Puskesmas Temon 1 - Google Spreadsheet', url: 'https://docs.google.com/spreadsheets/d/1Dhw7TRMbsz3lzXKufQQMfrSpmGM1u6Se0vJpP6fhytw/edit?resourcekey#gid=1052259077' },
  { name: 'Al-Kahf – Muhammad Sobri Maulana', url: 'https://muhammadsobrimaulana31.wordpress.com/2024/01/28/al-kahf/' },
  { name: 'Surat At Takwir Arab, Latin & Terjemah Bahasa Indonesia | Litequran.net', url: 'https://litequran.net/at-takwir' },
  { name: 'Maryam – Muhammad Sobri Maulana', url: 'https://muhammadsobrimaulana31.wordpress.com/2024/01/28/maryam/' },
  { name: 'An-Naba – Muhammad Sobri Maulana', url: 'https://muhammadsobrimaulana31.wordpress.com/2024/01/28/an-naba/' },
  { name: 'Al-Muzammil – Muhammad Sobri Maulana', url: 'https://muhammadsobrimaulana31.wordpress.com/2024/01/28/al-muzammil/' },
  { name: 'Al-Waqiah – Muhammad Sobri Maulana', url: 'https://muhammadsobrimaulana31.wordpress.com/2024/01/28/al-waqiah/' },
  { name: 'Test English - Prepare for your English exam', url: 'https://test-english.com/' },
  { name: 'Rutin Doa Pagi-Malam - Blog Dokter Musoma', url: 'https://blogdoktermusoma.blogspot.com/2023/07/rutin-doa-pagi-malam.html' },
  { name: 'Sobri PPDS - Google Dokumen', url: 'https://docs.google.com/document/d/155pPAbFhJtOmNrXAIAlk7Bcw9IzkKDfv3kU4WOuHqK0/edit?tab=t.0' },
  { name: 'Sobri Revolusi. 🟦 Senin — Bahu + Perut Bawah | by Muhammad Sobri Maulana | Aug, 2025 | Medium', url: 'https://muhammadsobrimaulana31.medium.com/sobri-revolusi-aa30dc02bce8?postPublishedType=initial' },
  { name: 'NotebookLM', url: 'https://notebooklm.google.com/' },
  { name: 'Latihan Sobri - Muhammad Sobri Maulana - Medium', url: 'https://muhammadsobrimaulana31.medium.com/latihan-sobri-956cbcaf3027?postPublishedType=initial' },
  { name: '(1) drill soal toefl - YouTube', url: 'https://www.youtube.com/results?search_query=drill+soal+toefl' },
  { name: 'Doa Ganteng Sobri', url: 'https://duniadoktersobri.blogspot.com/2025/03/doa-ganteng-sobri.html' },
  { name: 'Surat Al-Insyirah: Arab, Latin dan Terjemah Lengkap | Quran NU Online', url: 'https://quran.nu.or.id/al-insyirah' },
  { name: 'LYNK | Website Builder', url: 'https://lynk.id/v2/admin/dashboard' },
  { name: 'Threads', url: 'https://www.threads.net/?xmt=AQGznPWFWDlhBMyaNSbynJtgUSczYf17FM60lKT03OLBrUQ' },
  { name: '(1) Sinaps Medical Education - YouTube', url: 'https://www.youtube.com/@SinapsMedicalEducation/videos' },
  { name: 'Aerobik Penurunan berat badan dalam 7 hari - YouTube', url: 'https://www.youtube.com/watch?si=Eojk6E_fzlQrgvPf&v=i-Nley4RLTE&feature=youtu.be' },
  { name: 'Discover Clinical Medicine - MedSchool', url: 'https://medschool.co/' },
  { name: 'DoctorLib | Free online library on medicine books', url: 'https://doctorlib.info/' },
  { name: 'AddonForge - Timer for Forms - open', url: 'https://timer.addonforge.com/timer/1FAIpQLSeUprPcxKkKX04uA31u8yoR5D4n_VHqzeGp1QAsxYjeg7BdvA' },
  { name: 'Emergency Medicine Cases | EM Cases', url: 'https://emergencymedicinecases.com/' },
  { name: 'Al Mulk - Blog Dokter Sobri', url: 'https://blogdoktersobri.blogspot.com/2023/12/al-mulk.html' },
  { name: 'Surat At Tahrim Arab, Latin & Terjemah Bahasa Indonesia | Litequran.net', url: 'https://litequran.net/at-tahrim' },
  { name: 'Surat Al Fath Arab, Latin & Terjemah Bahasa Indonesia | Litequran.net', url: 'https://litequran.net/al-fath' },
  { name: 'Surat At Tariq Arab, Latin & Terjemah Bahasa Indonesia | Litequran.net', url: 'https://litequran.net/at-tariq' },
  { name: 'Surat Ad Dukhan Arab, Latin & Terjemah Bahasa Indonesia | Litequran.net', url: 'https://litequran.net/ad-dukhan' },
  { name: 'Surat Al Balad Arab, Latin & Terjemah Bahasa Indonesia | Litequran.net', url: 'https://litequran.net/al-balad' }
];
